name: CI
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  builds:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq nasm
      - name: install python dependencies
        run: |
          pip3 install mypy
      - name: cache pypy
        id: cache-pypy
        uses: actions/cache@v2
        with:
          path: pypy3.7-v7.3.5-linux64
          key: ${{ runner.os }}-pypy
      - name: install pypy from the official website
        if: steps.cache-pypy.outputs.cache-hit != 'true'
        run: |
          wget https://downloads.python.org/pypy/pypy3.7-v7.3.5-linux64.tar.bz2
          tar fvx pypy3.7-v7.3.5-linux64.tar.bz2
      - name: print version of pythons
        run: |
          python3 --version
          ./pypy3.7-v7.3.5-linux64/bin/pypy3 --version
      - name: run tests
        run: |
          mypy ./porth.py
          mypy ./test.py
          ./pypy3.7-v7.3.5-linux64/bin/pypy3 ./test.py run ./tests/
          ./pypy3.7-v7.3.5-linux64/bin/pypy3 ./test.py run ./examples/
          ./pypy3.7-v7.3.5-linux64/bin/pypy3 ./test.py run ./euler/
